apiVersion: apps/v1
kind: Deployment
metadata:
  name: dm-diploma-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      name: postgres
  template:
    metadata:
      labels:
        name: postgres
    spec:
      containers:
        - name: postgres
          image: macrosolid/postgresqldiploma:latest
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: "macrosolid"
            - name: POSTGRES_PASSWORD
              value: "secure-password"
            - name: POSTGRES_DB
              value: "djangodb"
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-volume-mount
      volumes:
        - name: postgres-volume-mount
          persistentVolumeClaim:
            claimName: postgresql-data-claim
      command: ["psql", "-d", $(POSTGRES_DB), "-U", $(POSTGRES_USER), "-a", "-f", myInsertFile]
---
# START Service
apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  type: ClusterIP
  ports:
    - port: 5432
  selector:
    name: postgres
# END SERVICE