serverFiles:
  alerts: |-
    groups:
    - name: example
      rules:
      - alert: HighErrorRate
        expr: job:request_latency_seconds:mean5m{job="myjob"} > 0.5
        for: 10m
        labels:
          severity: critical
        annotations:
          summary: High request latency
          description: This service is experiencing a high request latency.
wait: true